# Generated by Django 5.2.3 on 2025-07-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news_healines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('details', models.TextField()),
                ('published_on', models.DateField()),
                ('source', models.CharField(max_length=100)),
            ],
        ),
    ]
