# Generated by Django 5.2.3 on 2025-07-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_augur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_healines',
            name='hexenmeinung',
            field=models.CharField(default='nun', max_length=1000),
            preserve_default=False,
        ),
    ]
