# Generated by Django 5.2.3 on 2025-07-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_augur', '0002_news_healines_hexenmeinung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_healines',
            name='published_on',
            field=models.DateTimeField(),
        ),
    ]
